import { 
  Client, InventoryItem, WorkOrder, ServiceCatalogItem, 
  Employee, FinancialTransaction, Vehicle, CompanySettings, SystemAlert, Reminder, Reward, EmployeeTransaction
} from '../types';

// Valid UUIDs for compatibility with Supabase
export const MOCK_USER = {
  id: '11111111-1111-4111-8111-111111111111',
  name: 'Admin Cristal Care',
  email: 'admin@cristalcare.com',
  password: '123', // Senha simples para testes
  shopName: 'Cristal Care Autodetail'
};

export const MOCK_TENANT = {
  id: '22222222-2222-4222-8222-222222222222',
  name: 'Cristal Care Autodetail',
  slug: 'cristal-care',
  owner_id: MOCK_USER.id,
  plan_id: 'pro',
  status: 'active',
  created_at: new Date().toISOString()
};

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'c1',
    name: 'Roberto Silva',
    phone: '(11) 99999-1111',
    email: 'roberto@email.com',
    vehicles: [
      { id: 'v1', model: 'BMW 320i', plate: 'ABC-1234', color: 'Preto', year: '2023', size: 'medium' }
    ],
    ltv: 4500,
    visitCount: 5,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 dias atrás
    status: 'active',
    segment: 'vip',
    address: 'Rua das Flores, 123 - SP',
    notes: 'Cliente prefere café expresso. Gosta de produtos com acabamento fosco no painel.'
  },
  {
    id: 'c2',
    name: 'Ana Souza',
    phone: '(11) 98888-2222',
    email: 'ana@email.com',
    vehicles: [
      { id: 'v2', model: 'Jeep Compass', plate: 'XYZ-9876', color: 'Branco', year: '2022', size: 'large' }
    ],
    ltv: 350,
    visitCount: 1,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 45).toISOString(), // 45 dias atrás
    status: 'active',
    segment: 'new',
    address: 'Av. Paulista, 1000 - SP'
  },
  {
    id: 'c3',
    name: 'Carlos Oliveira',
    phone: '(11) 97777-3333',
    email: 'carlos@email.com',
    vehicles: [
      { id: 'v3', model: 'Honda Civic', plate: 'DEF-5678', color: 'Prata', year: '2021', size: 'medium' }
    ],
    ltv: 2200,
    visitCount: 8,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 70).toISOString(), // 70 dias atrás (Risco)
    status: 'churn_risk',
    segment: 'recurring',
    address: 'Rua Augusta, 500 - SP'
  },
  {
    id: 'c4',
    name: 'Fernanda Lima',
    phone: '(11) 96666-4444',
    email: 'fernanda@email.com',
    vehicles: [
      { id: 'v4', model: 'Porsche Macan', plate: 'PORS-9999', color: 'Azul', year: '2024', size: 'large' }
    ],
    ltv: 8500,
    visitCount: 12,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    status: 'active',
    segment: 'vip',
    address: 'Alameda Santos, 200 - SP'
  },
  {
    id: 'c5',
    name: 'Ricardo Mendes',
    phone: '(11) 95555-5555',
    email: 'ricardo@email.com',
    vehicles: [
      { id: 'v5', model: 'Fiat Toro', plate: 'TOR-1234', color: 'Vermelho', year: '2020', size: 'large' }
    ],
    ltv: 1200,
    visitCount: 4,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 100).toISOString(), // 100 dias (Inativo)
    status: 'inactive',
    segment: 'recurring',
    address: 'Rua da Consolação, 800 - SP'
  },
  {
    id: 'c6',
    name: 'Juliana Costa',
    phone: '(11) 94444-6666',
    email: 'juliana@email.com',
    vehicles: [
      { id: 'v6', model: 'HB20', plate: 'HB2-0000', color: 'Branco', year: '2019', size: 'medium' }
    ],
    ltv: 150,
    visitCount: 1,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    status: 'active',
    segment: 'new',
    address: 'Bairro Jardins - SP'
  },
  {
    id: 'c7',
    name: 'Marcos Vinicius',
    phone: '(11) 93333-7777',
    email: 'marcos@email.com',
    vehicles: [
      { id: 'v7', model: 'Toyota Corolla', plate: 'TOY-8888', color: 'Preto', year: '2023', size: 'medium' }
    ],
    ltv: 3200,
    visitCount: 6,
    lastVisit: new Date(Date.now() - 1000 * 60 * 60 * 24 * 65).toISOString(), // Risco
    status: 'churn_risk',
    segment: 'recurring',
    address: 'Vila Madalena - SP'
  }
];

export const MOCK_REMINDERS: Reminder[] = [
  {
    id: 'r1',
    clientId: 'c1',
    vehicleId: 'v1',
    serviceType: 'Manutenção Vitrificação',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 5).toISOString(), // Daqui a 5 dias
    status: 'pending',
    createdAt: new Date().toISOString(),
    autoGenerated: true
  },
  {
    id: 'r2',
    clientId: 'c3',
    vehicleId: 'v3',
    serviceType: 'Higienização Interna (6 meses)',
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(), // Atrasado 2 dias
    status: 'overdue',
    createdAt: new Date().toISOString(),
    autoGenerated: true
  },
  {
    id: 'r3',
    clientId: 'c4',
    vehicleId: 'v4',
    serviceType: 'Renovação de Proteção',
    dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 15).toISOString(),
    status: 'scheduled',
    createdAt: new Date().toISOString(),
    autoGenerated: true
  },
  {
    id: 'r4',
    clientId: 'c7',
    vehicleId: 'v7',
    serviceType: 'Polimento Comercial',
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // Atrasado
    status: 'overdue',
    createdAt: new Date().toISOString(),
    autoGenerated: true
  }
];

export const MOCK_INVENTORY: InventoryItem[] = [
  { id: 1, name: 'Shampoo Neutro', category: 'Químicos', stock: 5, unit: 'L', minStock: 2, costPrice: 45.00, status: 'ok' },
  { id: 2, name: 'Cera de Carnaúba', category: 'Acabamento', stock: 1, unit: 'un', minStock: 2, costPrice: 120.00, status: 'critical' },
  { id: 3, name: 'APC Multiuso', category: 'Químicos', stock: 10, unit: 'L', minStock: 5, costPrice: 35.00, status: 'ok' },
  { id: 4, name: 'Pano Microfibra', category: 'Acessórios', stock: 15, unit: 'un', minStock: 20, costPrice: 8.00, status: 'warning' },
  { id: 5, name: 'Composto Polidor (Corte)', category: 'Polimento', stock: 3, unit: 'kg', minStock: 1, costPrice: 150.00, status: 'ok' },
  { id: 6, name: 'Vitrificador 9H', category: 'Proteção', stock: 2, unit: 'un', minStock: 1, costPrice: 350.00, status: 'ok' }
];

export const MOCK_SERVICES: ServiceCatalogItem[] = [
  {
    id: 's1',
    name: 'Lavagem Detalhada',
    category: 'Lavagem',
    description: 'Lavagem técnica com descontaminação e proteção.',
    standardTimeMinutes: 60,
    active: true,
    returnIntervalDays: 30,
    showOnLandingPage: true,
    // @ts-ignore - Mocking nested property for DB loader
    price_matrix: {
        prices: { small: 80, medium: 100, large: 120, xl: 150 },
        consumption: [
            { inventoryId: 1, quantity: 100, usageUnit: 'ml' }, // Shampoo
            { inventoryId: 3, quantity: 50, usageUnit: 'ml' }   // APC
        ]
    }
  },
  {
    id: 's2',
    name: 'Polimento Técnico',
    category: 'Polimento',
    description: 'Correção de pintura em 3 etapas.',
    standardTimeMinutes: 240,
    active: true,
    returnIntervalDays: 180,
    showOnLandingPage: true,
    // @ts-ignore
    price_matrix: {
        prices: { small: 600, medium: 800, large: 1000, xl: 1200 },
        consumption: [
            { inventoryId: 5, quantity: 100, usageUnit: 'g' }, // Composto
            { inventoryId: 4, quantity: 1, usageUnit: 'un' }   // Pano (desgaste)
        ]
    }
  },
  {
    id: 's3',
    name: 'Higienização Interna',
    category: 'Interior',
    description: 'Limpeza profunda de estofados e carpetes.',
    standardTimeMinutes: 180,
    active: true,
    returnIntervalDays: 90,
    showOnLandingPage: true,
    // @ts-ignore
    price_matrix: {
        prices: { small: 350, medium: 450, large: 550, xl: 650 },
        consumption: [
            { inventoryId: 3, quantity: 300, usageUnit: 'ml' } // APC
        ]
    }
  },
  {
    id: 's4',
    name: 'Vitrificação Cerâmica',
    category: 'Proteção',
    description: 'Proteção de pintura por até 3 anos.',
    standardTimeMinutes: 300,
    active: true,
    returnIntervalDays: 365,
    showOnLandingPage: true,
    // @ts-ignore
    price_matrix: {
        prices: { small: 1200, medium: 1500, large: 1800, xl: 2200 },
        consumption: [
            { inventoryId: 6, quantity: 1, usageUnit: 'un' } // Vitrificador
        ]
    }
  }
];

export const MOCK_EMPLOYEES: Employee[] = [
  {
    id: 'e1',
    name: 'João Técnico',
    role: 'Detailer',
    pin: '1234',
    salaryType: 'commission',
    fixedSalary: 0,
    commissionRate: 30,
    commissionBase: 'gross',
    active: true,
    balance: 450.00
  },
  {
    id: 'e2',
    name: 'Maria Gerente',
    role: 'Manager',
    pin: '9999',
    salaryType: 'fixed',
    fixedSalary: 2500,
    commissionRate: 0,
    commissionBase: 'net',
    active: true,
    balance: 0
  }
];

export const MOCK_EMPLOYEES_TRANSACTIONS: EmployeeTransaction[] = [
  {
    id: 't1',
    employeeId: 'e1',
    type: 'commission',
    amount: 150.00,
    description: 'Comissão OS-1001 (Lavagem Detalhada)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(), // 1 day ago
    relatedWorkOrderId: 'OS-1001'
  },
  {
    id: 't2',
    employeeId: 'e1',
    type: 'advance',
    amount: 100.00,
    description: 'Vale Combustível',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(), // 5 days ago
  },
  {
    id: 't3',
    employeeId: 'e1',
    type: 'commission',
    amount: 240.00,
    description: 'Comissão OS-1002 (Polimento Parcial)',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(), // 3 days ago
  },
  {
    id: 't4',
    employeeId: 'e2',
    type: 'salary',
    amount: 2500.00,
    description: 'Salário Mensal',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(), // 15 days ago
  },
  {
    id: 't5',
    employeeId: 'e2',
    type: 'payment',
    amount: 2500.00,
    description: 'Pagamento Salário',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(), // Paid same day
  }
];

export const MOCK_WORK_ORDERS: WorkOrder[] = [
  {
    id: 'OS-1001',
    clientId: 'c1',
    vehicle: 'BMW 320i',
    plate: 'ABC-1234',
    service: 'Lavagem Detalhada',
    serviceId: 's1',
    serviceIds: ['s1'],
    status: 'Concluído',
    technician: 'João Técnico',
    deadline: 'Ontem',
    priority: 'medium',
    totalValue: 150.00,
    damages: [],
    vehicleInventory: { estepe: true, macaco: true, chaveRoda: true, tapetes: true, manual: true, antena: true, pertences: '' },
    dailyLog: [],
    qaChecklist: [],
    tasks: [],
    checklist: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), // Ontem
    paymentStatus: 'paid',
    paymentMethod: 'Pix',
    paidAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    npsScore: 10,
    npsComment: "Serviço impecável! O carro ficou novo de novo."
  },
  {
    id: 'OS-1002',
    clientId: 'c2',
    vehicle: 'Jeep Compass',
    plate: 'XYZ-9876',
    service: 'Polimento Técnico',
    serviceId: 's2',
    serviceIds: ['s2'],
    status: 'Em Andamento',
    technician: 'João Técnico',
    deadline: 'Hoje 18:00',
    priority: 'high',
    totalValue: 800.00,
    damages: [],
    vehicleInventory: { estepe: true, macaco: true, chaveRoda: true, tapetes: true, manual: true, antena: true, pertences: '' },
    dailyLog: [],
    qaChecklist: [],
    tasks: [],
    checklist: [],
    createdAt: new Date().toISOString(),
    paymentStatus: 'pending'
  },
  {
    id: 'OS-1000',
    clientId: 'c3',
    vehicle: 'Honda Civic',
    plate: 'DEF-5678',
    service: 'Higienização Interna',
    serviceId: 's3',
    serviceIds: ['s3'],
    status: 'Concluído',
    technician: 'Maria Gerente',
    deadline: 'Semana passada',
    priority: 'low',
    totalValue: 350.00,
    damages: [],
    vehicleInventory: { estepe: true, macaco: true, chaveRoda: true, tapetes: true, manual: true, antena: true, pertences: '' },
    dailyLog: [],
    qaChecklist: [],
    tasks: [],
    checklist: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    paymentStatus: 'paid',
    paymentMethod: 'Cartão Crédito',
    paidAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    npsScore: 9,
    npsComment: "Muito bom, atendimento rápido."
  }
];

export const MOCK_FINANCIALS: FinancialTransaction[] = [
  {
    id: 1,
    desc: 'Pagamento OS-1001',
    category: 'Serviços',
    amount: 150.00,
    netAmount: 150.00,
    fee: 0,
    type: 'income',
    date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    method: 'Pix',
    status: 'paid'
  },
  {
    id: 2,
    desc: 'Compra de Produtos',
    category: 'Estoque',
    amount: -250.00,
    netAmount: -250.00,
    fee: 0,
    type: 'expense',
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    dueDate: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    method: 'Cartão Crédito',
    status: 'paid'
  }
];

export const MOCK_ALERTS: SystemAlert[] = [
  {
    id: 'alert-1',
    type: 'cliente',
    message: 'Anomalia: 3 Clientes VIP não retornam há mais de 60 dias. Risco de Churn.',
    level: 'critico',
    resolved: false,
    createdAt: new Date().toISOString(),
    financialImpact: 4500,
    actionLabel: 'Recuperar Clientes',
    actionLink: '/marketing'
  },
  {
    id: 'alert-2',
    type: 'estoque',
    message: 'Estoque Crítico: Cera de Carnaúba (1 un). Risco de parada na operação.',
    level: 'critico',
    resolved: false,
    createdAt: new Date().toISOString(),
    financialImpact: 800,
    actionLabel: 'Repor Estoque',
    actionLink: '/inventory'
  },
  {
    id: 'alert-3',
    type: 'agenda',
    message: 'Oportunidade: Agenda de Quinta-feira com 40% de ociosidade.',
    level: 'info',
    resolved: false,
    createdAt: new Date().toISOString(),
    financialImpact: 2000,
    actionLabel: 'Criar Promoção Relâmpago',
    actionLink: '/marketing'
  },
  {
    id: 'alert-4',
    type: 'financeiro',
    message: 'Alerta: Queda de 12% no ticket médio comparado à semana anterior.',
    level: 'atencao',
    resolved: false,
    createdAt: new Date().toISOString(),
    financialImpact: 1200,
    actionLabel: 'Ver Relatório',
    actionLink: '/finance'
  }
];

export const MOCK_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    name: 'Lavagem Simples Grátis',
    description: 'Resgate uma lavagem simples completa.',
    requiredPoints: 1000,
    requiredLevel: 'silver',
    rewardType: 'free_service',
    gift: 'Lavagem Simples',
    active: true,
    createdAt: new Date().toISOString(),
    config: { gift: 'Lavagem Simples' }
  },
  {
    id: 'rew-2',
    name: '10% de Desconto',
    description: 'Desconto em qualquer serviço de estética.',
    requiredPoints: 500,
    requiredLevel: 'bronze',
    rewardType: 'discount',
    percentage: 10,
    active: true,
    createdAt: new Date().toISOString(),
    config: { percentage: 10 }
  },
  {
    id: 'rew-3',
    name: 'Kit Cera Líquida',
    description: 'Leve para casa nossa cera exclusiva.',
    requiredPoints: 1500,
    requiredLevel: 'gold',
    rewardType: 'gift',
    gift: 'Cera Líquida Premium',
    active: true,
    createdAt: new Date().toISOString(),
    config: { gift: 'Cera Líquida Premium' }
  },
  {
    id: 'rew-4',
    name: 'Polimento 50% OFF',
    description: 'Meio preço no polimento técnico completo.',
    requiredPoints: 2500,
    requiredLevel: 'platinum',
    rewardType: 'discount',
    percentage: 50,
    active: true,
    createdAt: new Date().toISOString(),
    config: { percentage: 50 }
  }
];

export const MOCK_EMPLOYEE_TRANSACTIONS = MOCK_EMPLOYEES_TRANSACTIONS;
