// ... existing types ...

// Atualização na interface de MarketingCampaign para suportar o novo sistema
export interface MarketingCampaign {
  id: string;
  name: string;
  type?: 'flash' | 'reactivation' | 'vip' | 'birthday' | 'promo' | 'combo' | 'custom';
  targetSegment: ClientSegment | 'all' | 'custom';
  selectedClientIds?: string[]; // Para salvar a seleção exata em rascunhos
  messageTemplate: string;
  channel?: 'whatsapp' | 'sms' | 'email';
  discount?: {
    type: 'percentage' | 'fixed';
    value: number;
  };
  sentCount: number;
  conversionCount?: number; 
  revenueGenerated?: number; 
  date: string;
  scheduledFor?: string; // Data de agendamento
  status: 'draft' | 'sent' | 'scheduled';
  costInTokens?: number;
}

export interface CampaignTemplate {
  id: string;
  label: string;
  category: 'retention' | 'sales' | 'operational' | 'relationship';
  defaultMessage: string;
  suggestedSegment?: ClientSegment | 'all';
  variables: string[];
}

// ... rest of the file (keep existing types)
export interface SystemAlert {
  id: string;
  type: 'agenda' | 'financeiro' | 'cliente' | 'profissional' | 'estoque';
  message: string;
  level: 'info' | 'atencao' | 'critico';
  actionLink?: string;
  actionLabel?: string;
  resolved: boolean;
  createdAt: string;
  financialImpact?: number;
  suggestedAction?: any;
}

export type VehicleSize = 'small' | 'medium' | 'large' | 'xl';

export const VEHICLE_SIZES: Record<VehicleSize, string> = {
  small: 'Pequeno (Hatch)',
  medium: 'Médio (Sedan)',
  large: 'Grande (SUV)',
  xl: 'Extra G. (Pickup)'
};

export interface ShopOwner {
  id: string;
  name: string;
  email: string;
  shopName: string;
}

export interface Vehicle {
  id: string;
  model: string;
  plate: string;
  color: string;
  year: string;
  size: VehicleSize;
}

export interface ServiceCatalogItem {
  id: string;
  name: string;
  description: string;
  category: string;
  active: boolean;
  standardTimeMinutes: number;
  returnIntervalDays?: number;
  imageUrl?: string;
  showOnLandingPage?: boolean;
}

export interface PriceMatrixEntry {
  serviceId: string;
  size: VehicleSize;
  price: number;
}

export interface Reminder {
  id: string;
  clientId: string;
  vehicleId: string;
  serviceType: string; 
  dueDate: string;
  status: 'pending' | 'sent' | 'scheduled' | 'overdue';
  createdAt: string;
  autoGenerated?: boolean;
}

export type ClientSegment = 'vip' | 'recurring' | 'inactive' | 'new' | 'standard';

export interface Client {
  id: string;
  name: string;
  phone: string;
  email: string;
  cep?: string;
  street?: string;
  number?: string;
  neighborhood?: string;
  city?: string;
  state?: string;
  address?: string;
  notes?: string;
  vehicles: Vehicle[];
  ltv: number; 
  lastVisit: string; 
  visitCount: number; 
  status: 'active' | 'inactive' | 'churn_risk'; 
  segment: ClientSegment; 
}

export interface InventoryItem {
  id: number;
  name: string;
  category: string;
  stock: number;
  unit: string;
  status: 'ok' | 'warning' | 'critical';
  minStock: number;
  costPrice: number; 
}

export interface ServiceConsumptionItem {
  inventoryId: number;
  quantity: number; 
  usageUnit: 'ml' | 'g' | 'un' | 'L' | 'kg'; 
}

export interface ServiceConsumption {
  serviceId: string;
  items: ServiceConsumptionItem[];
}

export interface ServiceRecipe {
  serviceName: string;
  items: {
    itemId: number;
    quantity: number;
  }[];
  maintenanceIntervalMonths?: number; 
}

export interface Employee {
  id: string;
  name: string;
  role: 'Manager' | 'Detailer' | 'Funileiro' | 'Lavador' | 'Pintor';
  pin: string;
  salaryType: 'commission' | 'fixed' | 'mixed'; 
  fixedSalary: number; 
  commissionRate: number;
  commissionBase: 'gross' | 'net';
  active: boolean;
  balance: number;
}

export interface TimeLog {
  id: string;
  taskId: string;
  employeeId: string;
  startTime: string;
  endTime?: string;
  durationMinutes?: number;
}

export interface Task {
  id: string;
  workOrderId: string;
  serviceId: string;
  serviceName: string;
  assignedTo: string;
  status: 'pending' | 'in_progress' | 'completed';
  standardTime: number;
  actualTime: number;
  commissionValue: number;
}

export interface EmployeeTransaction {
  id: string;
  employeeId: string;
  type: 'commission' | 'advance' | 'payment' | 'salary'; 
  amount: number;
  description: string;
  date: string;
  relatedWorkOrderId?: string;
}

export interface FinancialTransaction {
  id: number;
  desc: string;
  category: string;
  amount: number; 
  netAmount: number; 
  fee: number; 
  type: 'income' | 'expense';
  date: string; 
  dueDate: string; 
  method: string;
  installments?: number; 
  status: 'paid' | 'pending'; 
}

export interface DamagePoint {
  id: string;
  area: 'frente' | 'traseira' | 'lateral_esq' | 'lateral_dir' | 'teto' | 'rodas' | 'vidros' | 'interior';
  type: 'risco' | 'amassado' | 'mancha' | 'quebrado' | 'outro';
  description: string;
  photoUrl?: string; 
}

export interface VehicleInventory {
  estepe: boolean;
  macaco: boolean;
  chaveRoda: boolean;
  tapetes: boolean;
  manual: boolean;
  antena: boolean;
  pertences: string; 
}

export interface DailyLogEntry {
  id: string;
  date: string;
  stage: string;
  description: string;
  photos: string[];
  author: string;
}

export interface InsuranceDetails {
  isInsurance: boolean;
  insurerName?: string;
  deductibleAmount?: number; 
  insuranceCoveredAmount?: number; 
  claimNumber?: string; 
}

export interface QualityChecklistItem {
  id: string;
  label: string;
  checked: boolean;
  required: boolean;
}

export interface AdditionalItem {
  id: string;
  description: string;
  value: number;
}

export interface Discount {
  type: 'value' | 'percentage' | 'service';
  amount: number;
  description?: string;
  appliedServiceId?: string;
}

export type TierLevel = 'bronze' | 'silver' | 'gold' | 'platinum';

export interface TierConfig {
  id: TierLevel;
  name: string;
  minPoints: number;
  color: string;
  benefits: string[];
}

export interface GamificationConfig {
  enabled: boolean;
  levelSystem: boolean;
  pointsMultiplier: number;
  tiers: TierConfig[]; 
}

export interface Reward {
  id: string;
  name: string;
  description: string;
  requiredPoints: number;
  requiredLevel: TierLevel;
  rewardType: 'discount' | 'service' | 'gift' | 'free_service';
  value?: number;
  percentage?: number;
  serviceId?: string;
  gift?: string;
  active: boolean;
  createdAt: string;
  redeemedCount?: number;
}

export interface Redemption {
  id: string;
  clientId: string;
  rewardId: string;
  rewardName: string;
  code: string; 
  pointsCost: number;
  status: 'active' | 'used' | 'expired';
  redeemedAt: string;
  usedAt?: string;
  usedInWorkOrderId?: string;
}

export interface ClientPoints {
  clientId: string;
  totalPoints: number;
  currentLevel: number; 
  tier: TierLevel;
  lastServiceDate: string;
  servicesCompleted: number;
  pointsHistory: {
    id: string;
    workOrderId: string;
    points: number; 
    description: string;
    date: string;
  }[];
}

export interface FidelityCard {
  clientId: string;
  cardNumber: string;
  cardHolder: string;
  cardColor: 'blue' | 'purple' | 'emerald' | 'amber';
  qrCode: string;
  expiresAt: string;
  issueDate: string;
}

export interface ScopeItem {
    id: string;
    label: string;
    completed: boolean;
    type: 'main' | 'additional';
}

export interface WorkOrder {
  id: string;
  clientId: string;
  vehicle: string;
  plate: string;
  service: string; 
  serviceId?: string; 
  serviceIds?: string[]; 
  status: 'Aguardando Aprovação' | 'Aguardando' | 'Em Andamento' | 'Aguardando Peças' | 'Controle de Qualidade' | 'Concluído' | 'Entregue' | 'Cancelado';
  technician: string;
  deadline: string;
  priority: 'low' | 'medium' | 'high';
  
  totalValue: number;
  insuranceDetails?: InsuranceDetails;
  additionalItems?: AdditionalItem[]; 
  discount?: Discount;

  paymentStatus?: 'pending' | 'paid';
  paymentMethod?: string;
  paidAt?: string;

  damages: DamagePoint[];
  vehicleInventory: VehicleInventory;
  dailyLog: DailyLogEntry[];
  qaChecklist: QualityChecklistItem[];
  scopeChecklist?: ScopeItem[]; 
  
  tasks: Task[];
  
  clientSignature?: string; 
  createdAt: string;
  checklist: any[]; 
  
  npsScore?: number; 
  npsComment?: string;
  
  origin?: 'manual' | 'web_lead'; 
}

export interface WhatsappSessionInfo {
  status: 'disconnected' | 'scanning' | 'connected';
  qrCode?: string; 
  device?: {
    name: string;
    number: string;
    battery: number;
    avatarUrl: string;
  };
}

export interface WhatsappConfig {
  enabled: boolean;
  session: WhatsappSessionInfo;
  templates: {
    welcome: string;
    completion: string;
    nps: string;
    recall: string;
  };
}

export interface LandingPageConfig {
  enabled: boolean;
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  primaryColor: string;
  showServices: boolean;
  showTestimonials: boolean;
  whatsappMessage?: string;
}

export interface CompanyPreferences {
  theme: 'light' | 'dark';
  language: string;
  notifications: {
    lowStock: boolean;
    osUpdates: boolean;
    marketing: boolean;
    financial?: boolean;
    security?: boolean;
    channels?: {
      email: boolean;
      whatsapp: boolean;
      system: boolean;
    };
  };
}

export interface CompanySettings {
  name: string;
  slug: string;
  responsibleName: string;
  cnpj: string;
  email: string;
  phone: string;
  address: string;
  cep?: string;
  street?: string;
  number?: string;
  neighborhood?: string;
  city?: string;
  state?: string;
  
  logoUrl: string;
  website?: string;
  instagram?: string; 
  facebook?: string; 
  primaryColor?: string;
  initialBalance: number;
  whatsapp: WhatsappConfig; 
  landingPage: LandingPageConfig;
  preferences: CompanyPreferences;
  gamification: GamificationConfig;
}

export interface TokenTransaction {
  id: string;
  type: 'credit' | 'debit';
  amount: number;
  description: string;
  date: string;
}

export interface SubscriptionDetails {
  planId: 'starter' | 'pro' | 'enterprise' | 'trial';
  status: 'active' | 'past_due' | 'canceled' | 'trial';
  nextBillingDate: string;
  paymentMethod: string; 
  invoices: {
    id: string;
    date: string;
    amount: number;
    status: 'paid' | 'pending' | 'failed';
    pdfUrl: string;
  }[];
  tokenBalance: number;
  tokenHistory: TokenTransaction[];
}

export interface Notification {
  id: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
  type: 'info' | 'warning' | 'success' | 'error';
  link?: string;
}

export interface SaaSPlan {
  id: 'starter' | 'pro' | 'enterprise';
  name: string;
  price: number;
  features: string[];
  includedTokens: number;
  maxDiskSpace: number;
  active: boolean;
  highlight?: boolean;
  maxEmployees?: number;
}

export interface TokenPackage {
  id: string;
  name: string;
  tokens: number;
  price: number;
  active: boolean;
}

export interface SaaSTenant {
  id: string;
  name: string;
  responsibleName: string;
  email: string;
  phone: string;
  planId: 'starter' | 'pro' | 'enterprise';
  status: 'active' | 'suspended' | 'trial' | 'cancelled';
  joinedAt: string;
  nextBilling: string;
  tokenBalance: number;
  mrr: number;
  lastLogin: string;
  logoUrl?: string;
}

export interface SaaSTokenTransaction {
  id: string;
  tenantId: string;
  tenantName: string;
  type: 'purchase' | 'usage' | 'bonus' | 'plan_credit';
  amount: number;
  value?: number;
  description: string;
  date: string;
}

export interface AuthResponse {
  success: boolean;
  error?: {
    message: string;
    code?: string;
  } | null;
}
