export type VehicleSize = 'small' | 'medium' | 'large' | 'xl';

export const VEHICLE_SIZES: Record<VehicleSize, string> = {
  small: 'Pequeno (Hatch)',
  medium: 'Médio (Sedan)',
  large: 'Grande (SUV)',
  xl: 'Extra G. (Pickup)'
};

export interface Vehicle {
  id: string;
  model: string;
  plate: string;
  color: string;
  year: string;
  size: VehicleSize;
}

export interface ServiceCatalogItem {
  id: string;
  name: string;
  description: string;
  category: string;
  active: boolean;
  standardTimeMinutes: number;
  returnIntervalDays?: number;
  imageUrl?: string;
}

export interface PriceMatrixEntry {
  serviceId: string;
  size: VehicleSize;
  price: number;
}

export interface Reminder {
  id: string;
  clientId: string;
  vehicleId: string;
  serviceType: string; 
  dueDate: string;
  status: 'pending' | 'sent' | 'scheduled' | 'overdue';
  createdAt: string;
  autoGenerated?: boolean;
}

export type ClientSegment = 'vip' | 'recurring' | 'inactive' | 'new' | 'standard';

export interface Client {
  id: string;
  name: string;
  phone: string;
  email: string;
  address?: string;
  notes?: string;
  vehicles: Vehicle[];
  ltv: number; 
  lastVisit: string; 
  visitCount: number; 
  status: 'active' | 'inactive' | 'churn_risk'; 
  segment: ClientSegment; 
}

export interface MarketingCampaign {
  id: string;
  name: string;
  targetSegment: ClientSegment | 'all';
  messageTemplate: string;
  sentCount: number;
  conversionCount?: number; 
  revenueGenerated?: number; 
  date: string;
  status: 'draft' | 'sent' | 'scheduled';
}

export interface InventoryItem {
  id: number;
  name: string;
  category: string;
  stock: number;
  unit: string;
  status: 'ok' | 'warning' | 'critical';
  minStock: number;
  costPrice: number;
}

export interface ServiceRecipe {
  serviceName: string;
  items: {
    itemId: number;
    quantity: number;
  }[];
  maintenanceIntervalMonths?: number; 
}

export interface Employee {
  id: string;
  name: string;
  role: 'Manager' | 'Detailer' | 'Funileiro' | 'Lavador' | 'Pintor';
  pin: string;
  salaryType: 'commission' | 'fixed'; 
  fixedSalary: number; 
  commissionRate: number;
  commissionBase: 'gross' | 'net';
  active: boolean;
  balance: number;
}

export interface TimeLog {
  id: string;
  taskId: string;
  employeeId: string;
  startTime: string;
  endTime?: string;
  durationMinutes?: number;
}

export interface Task {
  id: string;
  workOrderId: string;
  serviceId: string;
  serviceName: string;
  assignedTo: string;
  status: 'pending' | 'in_progress' | 'completed';
  standardTime: number;
  actualTime: number;
  commissionValue: number;
}

export interface EmployeeTransaction {
  id: string;
  employeeId: string;
  type: 'commission' | 'advance' | 'payment' | 'salary'; 
  amount: number;
  description: string;
  date: string;
  relatedWorkOrderId?: string;
}

// --- FINANCIAL TYPES ---
export interface FinancialTransaction {
  id: number;
  desc: string;
  category: string;
  amount: number; // Valor Bruto (Positivo=Entrada, Negativo=Saída)
  netAmount: number; // Valor Líquido (após taxas)
  fee: number; // Taxa em R$
  type: 'income' | 'expense';
  date: string; // Data de Competência/Lançamento (YYYY-MM-DD)
  dueDate: string; // Data de Vencimento (YYYY-MM-DD)
  method: string;
  installments?: number; // Parcelas
  status: 'paid' | 'pending'; // Status do pagamento
}

export interface DamagePoint {
  id: string;
  area: 'frente' | 'traseira' | 'lateral_esq' | 'lateral_dir' | 'teto' | 'rodas' | 'vidros' | 'interior';
  type: 'risco' | 'amassado' | 'mancha' | 'quebrado' | 'outro';
  description: string;
  photoUrl?: string; 
}

export interface VehicleInventory {
  estepe: boolean;
  macaco: boolean;
  chaveRoda: boolean;
  tapetes: boolean;
  manual: boolean;
  antena: boolean;
  pertences: string; 
}

export interface DailyLogEntry {
  id: string;
  date: string;
  stage: string;
  description: string;
  photos: string[];
  author: string;
}

export interface InsuranceDetails {
  isInsurance: boolean;
  insurerName?: string;
  deductibleAmount?: number; 
  insuranceCoveredAmount?: number; 
  claimNumber?: string; 
}

export interface QualityChecklistItem {
  id: string;
  label: string;
  checked: boolean;
  required: boolean;
}

export interface AdditionalItem {
  id: string;
  description: string;
  value: number;
}

export interface Discount {
  type: 'value' | 'percentage' | 'service';
  amount: number;
  description?: string;
  appliedServiceId?: string;
}

export interface GamificationConfig {
  enabled: boolean;
  levelSystem: boolean;
  pointsMultiplier: number; // 1x, 1.5x, 2x etc
  rewardTier: 'bronze' | 'silver' | 'gold' | 'platinum';
}

export interface ClientPoints {
  clientId: string;
  totalPoints: number;
  currentLevel: number; // 1-5 levels
  tier: 'bronze' | 'silver' | 'gold' | 'platinum';
  lastServiceDate: string;
  servicesCompleted: number;
  pointsHistory: {
    id: string;
    workOrderId: string;
    points: number;
    description: string;
    date: string;
  }[];
}

export interface FidelityCard {
  clientId: string;
  cardNumber: string;
  cardHolder: string;
  cardColor: 'blue' | 'purple' | 'emerald' | 'amber';
  qrCode: string;
  expiresAt: string;
  issueDate: string;
}

export interface Reward {
  id: string;
  name: string;
  description: string;
  requiredPoints: number;
  requiredLevel: 'bronze' | 'silver' | 'gold' | 'platinum';
  rewardType: 'discount' | 'service' | 'gift' | 'free_service';
  value?: number;
  percentage?: number;
  serviceId?: string;
  gift?: string;
  active: boolean;
  createdAt: string;
  redeemedCount?: number;
}

export interface ScopeItem {
    id: string;
    label: string;
    completed: boolean;
    type: 'main' | 'additional';
}

export interface WorkOrder {
  id: string;
  clientId: string;
  vehicle: string;
  plate: string;
  service: string; 
  serviceId?: string; 
  serviceIds?: string[]; 
  status: 'Aguardando Aprovação' | 'Aguardando' | 'Em Andamento' | 'Aguardando Peças' | 'Controle de Qualidade' | 'Concluído' | 'Entregue' | 'Cancelado';
  technician: string;
  deadline: string;
  priority: 'low' | 'medium' | 'high';
  
  totalValue: number;
  insuranceDetails?: InsuranceDetails;
  additionalItems?: AdditionalItem[]; 
  discount?: Discount;

  damages: DamagePoint[];
  vehicleInventory: VehicleInventory;
  dailyLog: DailyLogEntry[];
  qaChecklist: QualityChecklistItem[];
  scopeChecklist?: ScopeItem[]; 
  
  tasks: Task[];
  
  clientSignature?: string; 
  createdAt: string;
  checklist: any[]; 
  
  npsScore?: number; 
  npsComment?: string;
  
  origin?: 'manual' | 'web_lead'; 
}

// --- SAAS & CONFIG TYPES ---

export interface WhatsappSessionInfo {
  status: 'disconnected' | 'scanning' | 'connected';
  qrCode?: string; 
  device?: {
    name: string;
    number: string;
    battery: number;
    avatarUrl: string;
  };
}

export interface WhatsappConfig {
  enabled: boolean;
  session: WhatsappSessionInfo;
  templates: {
    welcome: string;
    completion: string;
    nps: string;
    recall: string;
  };
}

export interface LandingPageConfig {
  enabled: boolean;
  heroTitle: string;
  heroSubtitle: string;
  heroImage: string;
  primaryColor: string;
  showServices: boolean;
  showTestimonials: boolean;
}

export interface CompanyPreferences {
  theme: 'light' | 'dark';
  language: string;
  notifications: {
    lowStock: boolean;
    osUpdates: boolean;
    marketing: boolean;
  };
}

export interface CompanySettings {
  name: string;
  responsibleName: string;
  cnpj: string;
  email: string;
  phone: string;
  address: string;
  logoUrl: string;
  website?: string;
  instagram?: string; 
  facebook?: string; 
  primaryColor?: string;
  initialBalance: number;
  whatsapp: WhatsappConfig; 
  landingPage: LandingPageConfig;
  preferences: CompanyPreferences;
  gamification: GamificationConfig;
}

export interface SubscriptionPlan {
  id: 'starter' | 'pro' | 'enterprise';
  name: string;
  price: number;
  features: string[];
  maxUsers: number;
}

export interface SubscriptionDetails {
  planId: 'starter' | 'pro' | 'enterprise';
  status: 'active' | 'past_due' | 'canceled' | 'trial';
  nextBillingDate: string;
  paymentMethod: string; 
  invoices: {
    id: string;
    date: string;
    amount: number;
    status: 'paid' | 'pending' | 'failed';
    pdfUrl: string;
  }[];
}
