/*
  # Create Social Posts Table
  
  ## Query Description:
  Creates a table to store social media posts generated by the Social Studio AI.
  
  ## Metadata:
  - Schema-Category: Structural
  - Impact-Level: Low
  - Requires-Backup: false
  - Reversible: true
  
  ## Structure Details:
  - Table: social_posts
  - Columns: id, tenant_id, work_order_id, image, caption, hashtags, platform, status, created_at
  - RLS: Enabled for tenant isolation
*/

create table if not exists public.social_posts (
  id uuid not null primary key,
  tenant_id uuid references public.tenants(id) on delete cascade,
  work_order_id uuid references public.work_orders(id) on delete set null,
  image text not null,
  caption text,
  hashtags text[],
  platform text,
  status text,
  created_at timestamptz default now()
);

alter table public.social_posts enable row level security;

create policy "Tenants can view own social posts"
  on public.social_posts for select
  using (auth.uid() in (select owner_id from public.tenants where id = social_posts.tenant_id));

create policy "Tenants can insert own social posts"
  on public.social_posts for insert
  with check (auth.uid() in (select owner_id from public.tenants where id = social_posts.tenant_id));

create policy "Tenants can update own social posts"
  on public.social_posts for update
  using (auth.uid() in (select owner_id from public.tenants where id = social_posts.tenant_id));

create policy "Tenants can delete own social posts"
  on public.social_posts for delete
  using (auth.uid() in (select owner_id from public.tenants where id = social_posts.tenant_id));
