-- Create Inventory Table if it doesn't exist
create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  tenant_id uuid references public.tenants(id) on delete cascade not null,
  name text not null,
  category text not null,
  stock numeric default 0,
  unit text default 'un',
  min_stock numeric default 0,
  cost_price numeric default 0,
  status text default 'ok',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.inventory enable row level security;

-- Policies
create policy "Enable read access for owners"
  on public.inventory for select
  using (auth.uid() in (select owner_id from public.tenants where id = inventory.tenant_id));

create policy "Enable insert access for owners"
  on public.inventory for insert
  with check (auth.uid() in (select owner_id from public.tenants where id = inventory.tenant_id));

create policy "Enable update access for owners"
  on public.inventory for update
  using (auth.uid() in (select owner_id from public.tenants where id = inventory.tenant_id));

create policy "Enable delete access for owners"
  on public.inventory for delete
  using (auth.uid() in (select owner_id from public.tenants where id = inventory.tenant_id));

-- Create indexes for performance
create index if not exists idx_inventory_tenant_id on public.inventory(tenant_id);
create index if not exists idx_inventory_status on public.inventory(status);
