/*
  # Fix Schema - Full Rebuild
  
  1. Drop existing tables to resolve conflicts and ensure clean state
  2. Create tables with correct relationships and columns (including owner_id)
  3. Enable RLS (Row Level Security)
  4. Create isolation policies
*/

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- DROP TABLES (Reverse order of dependencies to avoid errors)
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.financial_transactions CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.work_orders CASCADE;
DROP TABLE IF EXISTS public.vehicles CASCADE;
DROP TABLE IF EXISTS public.clients CASCADE;
DROP TABLE IF EXISTS public.tenants CASCADE;

-- 1. TENANTS (Lojas)
CREATE TABLE public.tenants (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    owner_id UUID REFERENCES auth.users(id) NOT NULL,
    name TEXT NOT NULL,
    slug TEXT,
    plan_id TEXT DEFAULT 'starter',
    status TEXT DEFAULT 'active',
    settings JSONB DEFAULT '{}'::jsonb,
    subscription JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. CLIENTS
CREATE TABLE public.clients (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT,
    email TEXT,
    address_data JSONB DEFAULT '{}'::jsonb,
    ltv NUMERIC DEFAULT 0,
    visit_count INTEGER DEFAULT 0,
    last_visit TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'active',
    segment TEXT DEFAULT 'new',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. VEHICLES
CREATE TABLE public.vehicles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE NOT NULL,
    model TEXT NOT NULL,
    plate TEXT NOT NULL,
    color TEXT,
    year TEXT,
    size TEXT DEFAULT 'medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. WORK ORDERS
CREATE TABLE public.work_orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    client_id UUID REFERENCES public.clients(id) NOT NULL,
    vehicle_plate TEXT,
    service_summary TEXT,
    status TEXT DEFAULT 'Aguardando',
    total_value NUMERIC DEFAULT 0,
    technician TEXT,
    deadline TEXT,
    payment_status TEXT DEFAULT 'pending',
    payment_method TEXT,
    nps_score INTEGER,
    json_data JSONB DEFAULT '{}'::jsonb, -- Stores damages, checklist, logs, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. INVENTORY
CREATE TABLE public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    stock NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'un',
    min_stock NUMERIC DEFAULT 5,
    cost_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'ok',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. FINANCIAL TRANSACTIONS
CREATE TABLE public.financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL, -- 'income' or 'expense'
    date DATE NOT NULL,
    method TEXT,
    status TEXT DEFAULT 'paid',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. SERVICES CATALOG
CREATE TABLE public.services (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    standard_time INTEGER DEFAULT 60,
    active BOOLEAN DEFAULT true,
    price_matrix JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. EMPLOYEES
CREATE TABLE public.employees (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    pin TEXT,
    salary_data JSONB DEFAULT '{}'::jsonb,
    active BOOLEAN DEFAULT true,
    balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ENABLE RLS
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- POLICIES

-- Tenants: Users can only see their own tenant
CREATE POLICY "Users can view own tenant" ON public.tenants
    FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "Users can update own tenant" ON public.tenants
    FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own tenant" ON public.tenants
    FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- Clients
CREATE POLICY "Tenant isolation for clients" ON public.clients
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Vehicles
CREATE POLICY "Tenant isolation for vehicles" ON public.vehicles
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Work Orders
CREATE POLICY "Tenant isolation for work_orders" ON public.work_orders
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Inventory
CREATE POLICY "Tenant isolation for inventory" ON public.inventory
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Financial
CREATE POLICY "Tenant isolation for financial" ON public.financial_transactions
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Services
CREATE POLICY "Tenant isolation for services" ON public.services
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Employees
CREATE POLICY "Tenant isolation for employees" ON public.employees
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()))
    WITH CHECK (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));
