/*
  # Esquema Inicial do Cristal Care ERP

  ## Descrição
  Este script cria a estrutura completa do banco de dados para o sistema SaaS.
  Inclui tabelas para Lojas (Tenants), Clientes, Veículos, Ordens de Serviço, Estoque e Financeiro.

  ## Metadata
  - Schema-Category: "Structural"
  - Impact-Level: "High"
  - Requires-Backup: false
  - Reversible: true

  ## Tabelas Criadas
  1. tenants (Lojas)
  2. clients (Clientes)
  3. vehicles (Veículos)
  4. work_orders (Ordens de Serviço)
  5. inventory (Estoque)
  6. services (Catálogo de Serviços)
  7. employees (Funcionários)
  8. financial_transactions (Financeiro)

  ## Segurança
  - RLS (Row Level Security) habilitado em todas as tabelas.
  - Políticas criadas para garantir que cada loja acesse apenas seus próprios dados.
*/

-- Habilitar extensão para UUIDs
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. TENANTS (LOJAS)
CREATE TABLE IF NOT EXISTS public.tenants (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    owner_id UUID REFERENCES auth.users(id), -- Link com usuário do Supabase Auth
    plan_id TEXT DEFAULT 'starter',
    status TEXT DEFAULT 'active',
    settings JSONB DEFAULT '{}'::jsonb, -- Configurações da empresa
    subscription JSONB DEFAULT '{}'::jsonb, -- Dados de assinatura e tokens
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. CLIENTS
CREATE TABLE IF NOT EXISTS public.clients (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    address_data JSONB DEFAULT '{}'::jsonb,
    ltv NUMERIC DEFAULT 0,
    visit_count INTEGER DEFAULT 0,
    last_visit TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'active',
    segment TEXT DEFAULT 'new',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. VEHICLES
CREATE TABLE IF NOT EXISTS public.vehicles (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE NOT NULL,
    model TEXT NOT NULL,
    plate TEXT NOT NULL,
    color TEXT,
    year TEXT,
    size TEXT DEFAULT 'medium',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. WORK ORDERS
CREATE TABLE IF NOT EXISTS public.work_orders (
    id TEXT PRIMARY KEY, -- Mantendo ID textual (ex: OS-1234) para compatibilidade
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    client_id UUID REFERENCES public.clients(id) ON DELETE SET NULL,
    vehicle_plate TEXT,
    service_summary TEXT,
    status TEXT DEFAULT 'Aguardando',
    total_value NUMERIC DEFAULT 0,
    technician TEXT,
    deadline TEXT,
    payment_status TEXT DEFAULT 'pending',
    payment_method TEXT,
    nps_score INTEGER,
    json_data JSONB DEFAULT '{}'::jsonb, -- Armazena damages, checklist, logs, etc.
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. INVENTORY
CREATE TABLE IF NOT EXISTS public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    stock NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'un',
    min_stock NUMERIC DEFAULT 0,
    cost_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'ok',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. SERVICES (CATALOG)
CREATE TABLE IF NOT EXISTS public.services (
    id TEXT PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    standard_time INTEGER DEFAULT 60,
    active BOOLEAN DEFAULT true,
    price_matrix JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. EMPLOYEES
CREATE TABLE IF NOT EXISTS public.employees (
    id TEXT PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    pin TEXT,
    salary_data JSONB DEFAULT '{}'::jsonb,
    active BOOLEAN DEFAULT true,
    balance NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. FINANCIAL TRANSACTIONS
CREATE TABLE IF NOT EXISTS public.financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) ON DELETE CASCADE NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL, -- 'income' or 'expense'
    date DATE NOT NULL,
    method TEXT,
    status TEXT DEFAULT 'paid',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ROW LEVEL SECURITY (RLS)
-- Habilitar RLS em todas as tabelas
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso (Simplificadas para MVP)
-- Assumindo que o usuário logado é o dono do tenant ou tem acesso a ele.
-- Para simplificar, vamos criar uma função que verifica se o usuário tem acesso ao tenant.

-- Política para Tenants: Usuário vê apenas seu próprio tenant
CREATE POLICY "Users can view own tenant" ON public.tenants
    FOR SELECT
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can update own tenant" ON public.tenants
    FOR UPDATE
    USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own tenant" ON public.tenants
    FOR INSERT
    WITH CHECK (auth.uid() = owner_id);

-- Política Genérica para outras tabelas:
-- O usuário deve ser dono do tenant ao qual o dado pertence.
-- (Em um sistema real, teríamos uma tabela de membros do tenant, mas aqui usamos owner_id direto no tenant)

CREATE POLICY "Access clients based on tenant ownership" ON public.clients
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access vehicles based on tenant ownership" ON public.vehicles
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access work_orders based on tenant ownership" ON public.work_orders
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access inventory based on tenant ownership" ON public.inventory
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access services based on tenant ownership" ON public.services
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access employees based on tenant ownership" ON public.employees
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

CREATE POLICY "Access financial_transactions based on tenant ownership" ON public.financial_transactions
    USING (tenant_id IN (SELECT id FROM public.tenants WHERE owner_id = auth.uid()));

-- Índices para performance
CREATE INDEX idx_clients_tenant ON public.clients(tenant_id);
CREATE INDEX idx_work_orders_tenant ON public.work_orders(tenant_id);
CREATE INDEX idx_financial_tenant ON public.financial_transactions(tenant_id);
