/*
  # CORREÇÃO COMPLETA DO SCHEMA (RESET)
  
  Este script irá:
  1. Limpar as tabelas existentes (para evitar conflitos de migração parcial).
  2. Recriar todas as tabelas com a estrutura correta (incluindo owner_id).
  3. Configurar as políticas de segurança (RLS).
*/

-- 1. LIMPEZA (Cuidado: Apaga dados existentes no Supabase para recriar a estrutura correta)
DROP TABLE IF EXISTS public.financial_transactions;
DROP TABLE IF EXISTS public.work_orders;
DROP TABLE IF EXISTS public.vehicles;
DROP TABLE IF EXISTS public.clients;
DROP TABLE IF EXISTS public.inventory;
DROP TABLE IF EXISTS public.services;
DROP TABLE IF EXISTS public.employees;
DROP TABLE IF EXISTS public.tenants;

-- Habilitar extensão de UUID
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. CRIAÇÃO DAS TABELAS

-- TENANTS (Empresas)
CREATE TABLE public.tenants (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    slug TEXT NOT NULL, -- Removido UNIQUE global temporariamente para facilitar testes, idealmente seria unique
    owner_id UUID REFERENCES auth.users(id) NOT NULL, -- VINCULO COM O USUÁRIO LOGADO
    status TEXT DEFAULT 'active',
    plan_id TEXT DEFAULT 'starter',
    settings JSONB DEFAULT '{}'::jsonb,
    subscription JSONB DEFAULT '{}'::jsonb
);

-- CLIENTS
CREATE TABLE public.clients (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    address_data JSONB DEFAULT '{}'::jsonb,
    ltv NUMERIC DEFAULT 0,
    visit_count INTEGER DEFAULT 0,
    last_visit TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'active',
    segment TEXT DEFAULT 'new',
    notes TEXT
);

-- VEHICLES
CREATE TABLE public.vehicles (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    client_id UUID REFERENCES public.clients(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    model TEXT NOT NULL,
    plate TEXT NOT NULL,
    color TEXT,
    year TEXT,
    size TEXT DEFAULT 'medium'
);

-- WORK ORDERS (OS)
CREATE TABLE public.work_orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    client_id UUID REFERENCES public.clients(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    vehicle_plate TEXT NOT NULL,
    service_summary TEXT,
    status TEXT DEFAULT 'Aguardando',
    total_value NUMERIC DEFAULT 0,
    technician TEXT,
    deadline TEXT,
    payment_status TEXT DEFAULT 'pending',
    payment_method TEXT,
    nps_score INTEGER,
    json_data JSONB DEFAULT '{}'::jsonb -- Armazena danos, checklist, logs, etc.
);

-- INVENTORY
CREATE TABLE public.inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    stock NUMERIC DEFAULT 0,
    unit TEXT DEFAULT 'un',
    min_stock NUMERIC DEFAULT 5,
    cost_price NUMERIC DEFAULT 0,
    status TEXT DEFAULT 'ok'
);

-- FINANCIAL TRANSACTIONS
CREATE TABLE public.financial_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    description TEXT NOT NULL,
    category TEXT,
    amount NUMERIC NOT NULL,
    type TEXT NOT NULL, -- 'income' ou 'expense'
    date DATE NOT NULL,
    method TEXT,
    status TEXT DEFAULT 'paid'
);

-- SERVICES CATALOG
CREATE TABLE public.services (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    description TEXT,
    standard_time INTEGER DEFAULT 60,
    active BOOLEAN DEFAULT true,
    price_matrix JSONB DEFAULT '[]'::jsonb
);

-- EMPLOYEES
CREATE TABLE public.employees (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    tenant_id UUID REFERENCES public.tenants(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    role TEXT,
    pin TEXT,
    salary_data JSONB DEFAULT '{}'::jsonb,
    active BOOLEAN DEFAULT true,
    balance NUMERIC DEFAULT 0
);

-- 3. SEGURANÇA (RLS)

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.tenants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

-- Políticas para TENANTS (O dono vê sua própria empresa)
CREATE POLICY "Users can view own tenant" ON public.tenants
    FOR SELECT USING (auth.uid() = owner_id);

CREATE POLICY "Users can update own tenant" ON public.tenants
    FOR UPDATE USING (auth.uid() = owner_id);

CREATE POLICY "Users can insert own tenant" ON public.tenants
    FOR INSERT WITH CHECK (auth.uid() = owner_id);

-- Políticas para outras tabelas (Acesso baseado no tenant_id que pertence ao owner)
-- Helper function para verificar propriedade do tenant
CREATE OR REPLACE FUNCTION public.is_tenant_owner(t_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.tenants
    WHERE id = t_id AND owner_id = auth.uid()
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Aplicar políticas usando a função auxiliar
CREATE POLICY "Owner access clients" ON public.clients
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access vehicles" ON public.vehicles
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access work_orders" ON public.work_orders
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access inventory" ON public.inventory
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access financial" ON public.financial_transactions
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access services" ON public.services
    FOR ALL USING (public.is_tenant_owner(tenant_id));

CREATE POLICY "Owner access employees" ON public.employees
    FOR ALL USING (public.is_tenant_owner(tenant_id));
